export const DEFAULT_CONTENT = {
  brand: "Anthony Studio",
  logoImage: "",
  navigation: {
    home: "首页",
    projects: "精选项目",
    blog: "联系",
    about: "关于我",
    resume: "个人优势",
  },
  eyebrow: "Visual / AI / Brand Designer",
  headline: "Brand Stories Through Visuals",
  description:
    "以品牌策略为起点，把视觉系统、AI 创意与商业场景连接起来，形成可识别、可传播、可持续生长的品牌体验。",
  ctaLabel: "查看项目",
  mediaMode: "video",
  videoUrl: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260405_170732_8a9ccda6-5cff-4628-b164-059c500a2b41.mp4",
  backgroundImage: "./portfolio/hero-poster-clean.webp",
  card: {
    year: "SHANGHAI / 2026",
    lead: "Visual",
    accent: "AI",
    tail: "Brand Designer",
    description: "视觉设计师 / AI 设计师 / 品牌设计师",
  },
  sectionSizes: {
    projects: 230,
    blog: 120,
    resume: 140,
    about: 80,
  },
  projects: {
    eyebrow: "Selected Work / 01-03",
    title: "Selected brand work.",
    description:
      "从品牌升级、全渠道视觉规范到电商内容落地，每个项目都围绕真实业务目标建立视觉系统。点击项目可进入完整案例。",
    items: [
      {
        index: "01",
        title: "滔搏运动 · 全渠道品牌升级",
        label: "Brand Upgrade / Retail",
        description:
          "覆盖 APP、小程序、全国终端与营销活动，以统一的视觉语言连接品牌、内容和线下零售体验。",
        metric: "Omnichannel Visual System",
        asset: "./portfolio/fragment-topsports.webp",
        galleryHeight: 76,
        gallery: [
          "./portfolio/project-01-cover.webp",
          "./portfolio/project-01-01.webp",
          "./portfolio/project-01-02.webp",
          "./portfolio/project-01-03.webp",
          "./portfolio/project-01-04.webp",
        ],
      },
      {
        index: "02",
        title: "Volga 敷尔佳 · 电商视觉规范",
        label: "E-commerce / Beauty",
        description:
          "建立跨平台电商视觉规范，用一致的版式、色彩和内容节奏提升品牌识别与商品转化效率。",
        metric: "Visual Standardization",
        asset: "./portfolio/fragment-volga.webp",
        galleryHeight: 76,
        gallery: [
          "./portfolio/project-02-cover.webp",
          "./portfolio/project-02-01.webp",
          "./portfolio/project-02-02.webp",
          "./portfolio/project-02-03.webp",
          "./portfolio/project-02-04.webp",
        ],
      },
      {
        index: "03",
        title: "福瑞达集团 · 品牌视觉落地",
        label: "Brand System / Medical Beauty",
        description:
          "整合集团与多品牌的线上线下触点，构建可复用的品牌视觉资产与全渠道内容体系。",
        metric: "0-1 Brand System",
        asset: "./portfolio/fragment-alva.webp",
        galleryHeight: 76,
        gallery: [
          "./portfolio/project-03-cover.webp",
          "./portfolio/project-03-01.webp",
          "./portfolio/project-03-02.webp",
          "./portfolio/project-03-03.webp",
          "./portfolio/project-03-04.webp",
        ],
      },
    ],
  },
  blog: {
    eyebrow: "Design Value",
    title: "Strategy, systems and AI.",
    description:
      "我关注的不只是单张视觉，而是品牌在不同媒介、渠道和团队中是否仍然保持一致、有效并且可持续。",
    items: [
      {
        category: "01 / STRATEGY",
        title: "品牌策略转译",
        meta: "Brand Positioning",
        asset: "./portfolio/project-03-02.webp",
        galleryHeight: 70,
        gallery: [
          "./portfolio/project-03-01.webp",
          "./portfolio/project-03-02.webp",
          "./portfolio/project-03-03.webp",
        ],
      },
      {
        category: "02 / SYSTEM",
        title: "全渠道视觉系统",
        meta: "Scalable Design",
        asset: "./portfolio/project-01-04.webp",
        galleryHeight: 70,
        gallery: [
          "./portfolio/project-01-01.webp",
          "./portfolio/project-01-02.webp",
          "./portfolio/project-01-04.webp",
        ],
      },
      {
        category: "03 / AI",
        title: "AI 创意生产",
        meta: "Rapid Exploration",
        asset: "./portfolio/project-02-04.webp",
        galleryHeight: 70,
        gallery: [
          "./portfolio/project-02-01.webp",
          "./portfolio/project-02-03.webp",
          "./portfolio/project-02-04.webp",
        ],
      },
    ],
  },
  resume: {
    eyebrow: "Capabilities",
    title: "Brand thinking. Commercial execution.",
    description:
      "既能从策略和系统层建立方向，也能深入电商、内容与终端场景完成落地，并借助 AI 提升探索与制作效率。",
    items: [
      {
        step: "01",
        title: "品牌视觉系统",
        description: "从品牌定位到识别、版式、色彩和视觉资产，建立一致且可扩展的系统。",
        asset: "./portfolio/project-03-cover.webp",
        galleryHeight: 70,
        gallery: ["./portfolio/project-03-01.webp", "./portfolio/project-03-02.webp"],
      },
      {
        step: "02",
        title: "电商视觉设计",
        description: "理解平台规则、商品信息与转化目标，构建高效且有品牌感的电商内容。",
        asset: "./portfolio/project-02-01.webp",
        galleryHeight: 70,
        gallery: ["./portfolio/project-02-01.webp", "./portfolio/project-02-02.webp"],
      },
      {
        step: "03",
        title: "AI 创意与生图",
        description: "将 AI 用于概念发散、视觉提案、场景延展和批量内容生产。",
        asset: "./portfolio/project-02-04.webp",
        galleryHeight: 70,
        gallery: ["./portfolio/project-02-03.webp", "./portfolio/project-02-04.webp"],
      },
      {
        step: "04",
        title: "全渠道规范",
        description: "统一线上、线下、社媒、终端与活动触点，降低协作和复用成本。",
        asset: "./portfolio/project-01-04.webp",
        galleryHeight: 70,
        gallery: ["./portfolio/project-01-02.webp", "./portfolio/project-01-04.webp"],
      },
      {
        step: "05",
        title: "商业数据洞察",
        description: "把业务指标和用户反馈转化为设计判断，让审美与结果同时成立。",
        asset: "./portfolio/project-03-03.webp",
        galleryHeight: 70,
        gallery: ["./portfolio/project-03-03.webp", "./portfolio/project-03-04.webp"],
      },
      {
        step: "06",
        title: "跨文化设计",
        description: "具备中国与日本设计团队经验，能够处理不同文化语境下的品牌表达。",
        asset: "./portfolio/project-01-01.webp",
        galleryHeight: 70,
        gallery: ["./portfolio/project-01-01.webp", "./portfolio/about-resume.webp"],
      },
      {
        step: "07",
        title: "内容与动效",
        description: "用节奏、叙事和动态表达提升静态系统在数字媒介中的传播力。",
        asset: "./portfolio/project-02-03.webp",
        galleryHeight: 70,
        gallery: ["./portfolio/project-02-02.webp", "./portfolio/project-02-03.webp"],
      },
      {
        step: "08",
        title: "设计落地管理",
        description: "从方向、规范到执行复盘，保证复杂项目在多团队环境中稳定落地。",
        asset: "./portfolio/project-01-03.webp",
        galleryHeight: 70,
        gallery: ["./portfolio/project-01-03.webp", "./portfolio/contact.webp"],
      },
    ],
  },
  about: {
    eyebrow: "About Anthony",
    title: "I build visual systems that turn brand character into business momentum.",
    name: "朱宇航 / Anthony",
    role: "Visual Designer · AI Designer · Brand Designer",
    bio:
      "五年品牌全链路视觉设计经验，专注美妆护肤、运动零售与新消费赛道。曾参与外资零售、国企医美、日本设计工作室与上市医美品牌项目，擅长从品牌升级、0-1 体系搭建到全渠道商业落地。",
    stats: [
      { value: "05+", label: "Years in design" },
      { value: "03", label: "Selected cases" },
      { value: "04", label: "Industry contexts" },
      { value: "02", label: "Cross-cultural markets" },
    ],
    email: "342140859@qq.com",
    wechat: "",
    location: "Shanghai · Open for selected collaborations",
    image: "./portfolio/portrait.webp",
    galleryHeight: 76,
    gallery: [
      "./portfolio/about-resume.webp",
      "./portfolio/hero-poster.webp",
      "./portfolio/project-01-cover.webp",
      "./portfolio/project-02-cover.webp",
    ],
  },
};

export const CONTENT_STORAGE_KEY = "codenest-content-v2";
